{"name": "test_one", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_pytest.py:14: AssumptionFailure\n>>\tpytest.assume(1 == 4)\nAssertionError: assert False\n\ntest_pytest.py:15: AssumptionFailure\n>>\tpytest.assume(2 == 4)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_pytest.py:14: AssumptionFailure\nE               >>\tpytest.assume(1 == 4)\nE               AssertionError: assert False\nE               \nE               test_pytest.py:15: AssumptionFailure\nE               >>\tpytest.assume(2 == 4)\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:718: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "4b6ce72d-edf3-4e17-ad65-553b986b5582-attachment.txt", "type": "text/plain"}], "start": 1627228117988, "stop": 1627228118020, "uuid": "6d43bbf8-7086-4433-b696-a42d5a10d59f", "historyId": "cae720059d216307f0ad13fafb1da3e9", "testCaseId": "70dae12d191995a1b502a849c4587608", "fullName": "test_pytest.TestDemo#test_one", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "LAPTOP-CKTC9IDM"}, {"name": "thread", "value": "16832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}