{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.TestDemo1 object at 0x0000024E003F82E8>\n\n    def test_b(self):\n        print(\"start to run test_b\")\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest.py:39: AssertionError"}, "attachments": [{"name": "stdout", "source": "b1ecefbc-248b-4e91-bb77-579633e103ee-attachment.txt", "type": "text/plain"}], "start": 1627228118079, "stop": 1627228118080, "uuid": "58db6672-2824-4c4c-a90c-ba2708e5087a", "historyId": "26540ea187e219ec0403caab8bdc458a", "testCaseId": "ea9d2986a207c004dbe3e7bbe985c5e9", "fullName": "test_pytest.TestDemo1#test_b", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestDemo1"}, {"name": "host", "value": "LAPTOP-CKTC9IDM"}, {"name": "thread", "value": "16832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}