{"name": "test_login_failed_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_pytest_allure_feature_story.TestLogin object at 0x000002AFD4F91710>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failed_b(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登陆\")\n        with allure.step(\"点击登陆之后登陆失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_pytest_allure_feature_story.py:33: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1627298750768, "stop": 1627298750768}, {"name": "点击密码", "status": "passed", "start": 1627298750768, "stop": 1627298750768}, {"name": "点击登陆之后登陆失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\Work\\Pycharm-workspace\\MyFirstProject\\test_pytest\\test_pytest_allure_feature_story.py\", line 33, in test_login_failed_b\n    assert '1' == 1\n"}, "start": 1627298750768, "stop": 1627298750768}], "attachments": [{"name": "stdout", "source": "6efce0c9-64ac-4d15-afb9-558f79ae40e1-attachment.txt", "type": "text/plain"}], "start": 1627298750768, "stop": 1627298750769, "uuid": "67e2afc0-15bc-4cb8-a138-553d0ab38eac", "historyId": "6d383752426834e77b3b524ef13b3821", "testCaseId": "59f66f869ffedae19e748fda1eb07324", "fullName": "test_pytest_allure_feature_story.TestLogin#test_login_failed_b", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登陆模块"}, {"name": "suite", "value": "test_pytest_allure_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-CKTC9IDM"}, {"name": "thread", "value": "19012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest_allure_feature_story"}]}